### ISSUE TITLE
Replace pkg_resources with importlib_metadata

### ISSUE THREAD

**Issue by jayvdb** [moremoban/pypifs#1]
pkg_resources is unusable.  The page about importlib_metadata explains why it is so bad, or see bugs in setuptools repo.
https://github.com/moremoban/moban/pull/302#discussion_r307960169

https://importlib-metadata.readthedocs.io/en/latest/using.html

```py
import importlib_metadata
importlib_metadata.distribution("fs")._path
PosixPath('/usr/local/lib/python3.7/site-packages/fs-2.1.2.dist-info')
```

**Comment by jayvdb** [comment]
Also there are a bunch of issues related to using `__file__` instead of using `__path__` , and both may be `None`.
But using importlib_metadata is the first step in correct determination of the locations for a package.

**Comment by chfw** [comment]
My effort is spreaded to wide. Any help from open source community in time(before I turn my head around) is appreciated.

**Comment by jayvdb** [comment]
ya, understood.  These issues are all optional - they can be done after we get pyfs operational.
